/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DjsRouteImport } from './routes/djs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenueSlugRouteImport } from './routes/venue.$slug'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as DjSlugRouteImport } from './routes/dj.$slug'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DjsRoute = DjsRouteImport.update({
  id: '/djs',
  path: '/djs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueSlugRoute = VenueSlugRouteImport.update({
  id: '/venue/$slug',
  path: '/venue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DjSlugRoute = DjSlugRouteImport.update({
  id: '/dj/$slug',
  path: '/dj/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/djs': typeof DjsRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRoute
  '/dj/$slug': typeof DjSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/venue/$slug': typeof VenueSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/djs': typeof DjsRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRoute
  '/dj/$slug': typeof DjSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/venue/$slug': typeof VenueSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/djs': typeof DjsRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRoute
  '/dj/$slug': typeof DjSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/venue/$slug': typeof VenueSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/djs'
    | '/events'
    | '/sitemap.xml'
    | '/venues'
    | '/dj/$slug'
    | '/event/$slug'
    | '/venue/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/djs'
    | '/events'
    | '/sitemap.xml'
    | '/venues'
    | '/dj/$slug'
    | '/event/$slug'
    | '/venue/$slug'
  id:
    | '__root__'
    | '/'
    | '/djs'
    | '/events'
    | '/sitemap.xml'
    | '/venues'
    | '/dj/$slug'
    | '/event/$slug'
    | '/venue/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DjsRoute: typeof DjsRoute
  EventsRoute: typeof EventsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenuesRoute: typeof VenuesRoute
  DjSlugRoute: typeof DjSlugRoute
  EventSlugRoute: typeof EventSlugRoute
  VenueSlugRoute: typeof VenueSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/djs': {
      id: '/djs'
      path: '/djs'
      fullPath: '/djs'
      preLoaderRoute: typeof DjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$slug': {
      id: '/venue/$slug'
      path: '/venue/$slug'
      fullPath: '/venue/$slug'
      preLoaderRoute: typeof VenueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj/$slug': {
      id: '/dj/$slug'
      path: '/dj/$slug'
      fullPath: '/dj/$slug'
      preLoaderRoute: typeof DjSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DjsRoute: DjsRoute,
  EventsRoute: EventsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenuesRoute: VenuesRoute,
  DjSlugRoute: DjSlugRoute,
  EventSlugRoute: EventSlugRoute,
  VenueSlugRoute: VenueSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
